- package-lock.json
- package.json
- web-src/src/components/ApplicationProvider.js
- web-src/src/components/Editor.js
> feat: first version of prompt editor

- .eslintrc.cjs
- package-lock.json
- package.json
- web-src/src/components/Editor.js
> feat: add syntax highlighting

- package-lock.json
- package.json
- web-src/src/components/App.js
- web-src/src/components/ContainerView.js
- web-src/src/icons/WriteIcon.js
> Add columns layout structure.

- package-lock.json
- package.json
- web-src/src/components/App.js
- web-src/src/components/ApplicationProvider.js
- web-src/src/components/ContainerView.js
- web-src/src/components/CreativitySelector.js
- web-src/src/components/CreativitySlider.js
- web-src/src/components/Editor.js
- web-src/src/components/FavoritesSection.js
- web-src/src/components/GenerateButton.js
- web-src/src/components/ParametersView.js
- web-src/src/components/PromptTemplatePicker.js
- web-src/src/components/PromptTemplateSelector.js
- web-src/src/components/ResultsView.js
- web-src/src/components/VariationsSection.js
- web-src/src/index.css
- web-src/src/index.js
- web-src/src/state/ExpressionsState.js
- web-src/src/state/GenerationInProgressState.js
- web-src/src/state/GenerationResultsState.js
- web-src/src/state/NewVariationsSelector.js
- web-src/src/state/ParametersState.js
- web-src/src/state/PromptState.js
- web-src/src/state/PromptTemplateState.js
- web-src/src/state/PromptTemplatesState.js
- web-src/src/state/ShowParametersState.js
- web-src/src/state/ShowPromptState.js
- web-src/src/state/SourceViewState.js
- web-src/src/state/TemperatureState.js
Introduce [Recoil](https://github.com/facebookexperimental/Recoil) for centralized state management.
> introduce app state management

- web-src/src/components/ConsentDialog.js
- web-src/src/rum.js
> feat: collect consent rum data

- web-src/src/components/PromptTemplateCard.js
> fix: prompt card key error

- web-src/src/components/FavoriteCard.js
- web-src/src/components/GenerateButton.js
- web-src/src/components/ResultCard.js
- web-src/src/helpers/CreateVariants.js
- web-src/src/helpers/CreateVariants.test.js
- web-src/src/helpers/ExportPrompt.js
- web-src/src/helpers/ExportPrompt.test.js
> fix: [63] copy html to clipboard

- web-src/src/components/ResultCard.js
> user tracking thumbs up & down

- web-src/src/components/ResultCard.js
> feat: Remove copy icon from prompt and change re-use icon

- web-src/src/components/LegalTermsLink.js
> feat: Consent modal doesn't show hyperlink (even though it has one)

- web-src/src/components/ResultCard.js
> feat: Star hover should match left nav

- web-src/src/components/DescriptionLabel.js
- web-src/src/components/InputsView.js
- web-src/src/components/SpreadSheetPicker.js
> feat: Prompt input tooltip does not wrap around

- web-src/src/components/InputsView.js
- web-src/src/components/TemperatureSlider.js
> feat: Temperature should be under Advanced add a description

- web-src/src/components/PromptResultCard.js
- web-src/src/components/TemperatureSlider.js
> feat: fixed issue #126 and #54

- web-src/src/components/GenerateButton.js
> feat: fixed minor typo in the contextual help of 'Generate' button

- package-lock.json
- web-src/src/components/FavoriteVariantCard.js
> feat: add copy toast to Favorites view

- .env.template
- .gitignore
- README.md
> Update env configuration instructions

- web-src/src/state/TemperatureState.js
> feat: Max out temperature to 1.2

- web-src/src/components/App.js
- web-src/src/components/ConsentDialog.js
> feat: refactor user consent to display conditional no access message

- web-src/src/components/App.js
- web-src/src/components/ConsentDialog.js
> Fix excshell groupid

- web-src/src/components/ConsentDialog.js
> fix: Updated EXC_SHELL_GROUP_ID in ConsentDialog.js

- web-src/src/components/App.js
> chore: change no access message

- web-src/src/components/LinkLabel.js
- web-src/src/components/MainSidePanel.js
- web-src/src/components/PromptEditor.js
- web-src/src/components/PromptTemplateCard.js
- web-src/src/components/PromptTemplateLibraryPanel.js
- web-src/src/components/WelcomeBanner.js
> Accessibility improvements

- web-src/src/components/FavoriteVariantCard.js
- web-src/src/components/GenerateButton.js
- web-src/src/components/PromptResultCard.js
- web-src/src/components/PromptTemplateLibraryPanel.js
- web-src/src/helpers/ResultsParser.js
- web-src/src/helpers/ResultsParser.test.js
> feat: AI Rationale is being copied to clipboard

- web-src/src/components/SavePromptButton.js
> fix: Add step 5 in SavePromptButton.js

- web-src/src/components/FavoriteVariantCard.js
- web-src/src/components/GenerateButton.js
- web-src/src/components/PromptResultCard.js
- web-src/src/components/PromptTemplateLibraryPanel.js
- web-src/src/helpers/ResultsParser.js
- web-src/src/helpers/ResultsParser.test.js
> revert: AI Rationale is being copied to clipboard

- .env.template
- README.md
- app.config.yaml
- web-src/src/components/PromptTemplateLibraryPanel.js
- web-src/src/helpers/ResultsParser.test.js
> chore: code cleanup

- package.json
> chore: update version in package.json

- .husky/pre-commit
- package.json
- scripts/prompt-generator.js
- scripts/zip-examples.js
- Only regenerate the bundled prompts library if the prompt files have changed
- Only zip example files if example files have changed
> Refactor bundled and example file generators

- web-src/src/components/ConsentDialog.js
- web-src/src/components/GenerateButton.js
- web-src/src/components/LegalTermsLink.js
> feat: update legal information in the consent dialog and popup beside 'Generate'

- web-src/src/components/FavoriteVariantCard.js
> fix: updated the icons in 'Favorites' panel

- web-src/src/components/App.js
- web-src/src/components/ClickableImage.js
- web-src/src/components/MainSidePanel.js
- web-src/src/state/MainSidePanelState.js
https://experience.adobe.com/?shell_source=dev&ref=genai-plugin-dev&repo=wknd&owner=hlxsites&project=WKND#/@sitesinternal/aem/generate-variations
> feat: Make responsive to deal with smaller screens

- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_qa.yml
- README.md
> fix: Added missing HEC token environment variable.

- package.json
> fix: actions are excluded from coverage report

- web-src/src/components/GenerateButton.js
> collect rum num of generated variants as target

- web-src/src/components/PromptEditor.js
> feat: SITES-19436 Prompt and Trusted Source Documents

- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_qa.yml
- web-src/src/services/ExpressSDKService.js
> fix: Pinned Express SDK URL to v4.1.14

- scripts/prompt-generator.js
> fix: git branch is not resolved when using tags

- actions/Network.js
- app.config.yaml
- package.json
> feat: set timeout to 55 seconds

- prompt-templates/card.prompt
- prompt-templates/cart-abandonment.prompt
- prompt-templates/faq.prompt
- prompt-templates/headline.prompt
- prompt-templates/hero.prompt
- prompt-templates/rewrite.prompt
- prompt-templates/tile.prompt
> chore: Change the default number of variations to 3

- package-lock.json
- package.json
- web-src/src/helpers/UrlHelper.js
- web-src/src/services/FirefallService.js
> fix: 503 error due to action served from 'adobe-static.net'

- package.json
> fix: build prompts before review

- web-src/src/components/PromptResultCard.l10n.js
- web-src/src/components/__localization__/PromptResultCard.l10n/de_de.json
- web-src/src/components/__localization__/PromptResultCard.l10n/en_us.json
- web-src/src/components/__localization__/PromptResultCard.l10n/es_es.json
- web-src/src/components/__localization__/PromptResultCard.l10n/fr_fr.json
- web-src/src/components/__localization__/PromptResultCard.l10n/it_it.json
- web-src/src/components/__localization__/PromptResultCard.l10n/ja_jp.json
- web-src/src/components/__localization__/PromptResultCard.l10n/jl10n.json
- web-src/src/components/__localization__/PromptResultCard.l10n/ko_kr.json
- web-src/src/components/__localization__/PromptResultCard.l10n/pt_br.json
- web-src/src/components/__localization__/PromptResultCard.l10n/zh_cn.json
- web-src/src/components/__localization__/PromptResultCard.l10n/zh_tw.json
> fix: Minor typo for text localization

- .github/workflows/pr_test_frontend.yml
- scripts/deploy.js
- scripts/generate-prompts.js
- scripts/utils.js
This PR improves how we identify the current GitHub branch, fixing issues when running in GitHub Actions.
> fix: build fails in github actions

- actions/FirefallClient.js
- actions/complete/index.js
- web-src/src/components/GenerateButton.js
- web-src/src/helpers/ImageHelper.js
- web-src/src/helpers/ResultsParser.js
- web-src/src/services/FirefallService.js
Reverts adobe/aem-genai-assistant#235
> Revert "chore: update model name"

- web-src/src/components/MainSidePanel.js
https://jira.corp.adobe.com/browse/SITES-20024
https://experience-qa.adobe.com/?devMode=true&shell_source=qa&shell_ims=prod&app_workspace=movevernumber2#/@sitesinternal/aem/generate-variations/
**Before:**
**After:**
> Move the version number into Copyright

- web-src/src/components/MainSidePanel.js
https://experience-qa.adobe.com/?devMode=true&shell_source=qa&shell_ims=prod&app_workspace=removeoldvernumber#/@sitesinternal/aem/generate-variations/
> Remove the old version number

- app.config.yaml
- hooks/post-app-run.js
Displays the correct URL of your locally deployed AEM Generate Variations application without having to hunt for links.
> feat: Configure post-app-run hook to display the correct app url

- web-src/src/components/ApplicationProvider.js
- web-src/src/components/GenerateButton.js
- web-src/src/components/MainSidePanel.js
- web-src/src/components/PromptResultCard.js
- web-src/src/components/PromptTemplatesView.js
- web-src/src/components/SavePromptButton.js
- web-src/src/helpers/SettingsHelper.js
- web-src/src/state/PromptTemplatesState.js
- web-src/src/state/PromptTemplatesState.test.js
- web-src/src/state/RunMode.js
1. Open [default mode app](https://experience-qa.adobe.com/?devMode=true&shell_source=qa&shell_ims=prod&app_workspace=promptsavingfix#/aem/generate-variations/
) in one tab.
1. Open [cf mode app](https://experience-qa.adobe.com/?devMode=true&shell_source=qa&shell_ims=prod&aemHost=author-p128738-e1257421.adobeaemcloud.com&fragmentId=4db9a98e-8660-4f5c-8bf4-3afb5efc88d3&app_workspace=promptsavingfix#/@sitesinternal/aem/generate-variations/) in another tab.
1. Create a few private and shared prompts in both tabs.
1. Try to delete, update, and add prompts on one tab.
1. Switch to another tab and, **without refreshing the page**, try to create a new prompt.
1. Refresh both tabs and check that all prompts are displayed as expected.
> feat: reconcile settings before saving prompts

- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_qa.yml
- .github/workflows/pr_test_frontend.yml
- package-lock.json
- package.json
- scripts/deploy.js
- web-src/index.html
Fixed issue with the development URL -> it should follow the pattern `?shell_source=workspace&workspace=<workspace>`
Run `npm run deploy`.
> SITES-21864: Copy/paste on QA broken

- scripts/deploy.js
https://jira.corp.adobe.com/browse/SITES-21924
> fix: Release deployment doesn't work

- actions/FirefallClient.js
Add `"store_context: true"` to have `query_id` to fix a feedback button.
It was a breaking change in Firefall API recently, see [the wiki docs](https://wiki.corp.adobe.com/display/adobeDS/Tutorial+-+Using+Firefall+Generative+APIs#TutorialUsingFirefallGenerativeAPIs-APIFormat:POST/v1/completionswithstore_context=true) , in order to have `query_id`, and a request details stored, the `store_context` flag should be set to `true`.
Test URL: https://experience-qa.adobe.com/?devMode=true&shell_source=workspace&workspace=fixfeedbackbutton&shell_ims=prod#/aem/generate-variations/
https://jira.corp.adobe.com/browse/SITES-22066
> Add "store_context: true" to have query_id to fix a feedback button

- scripts/deploy.js
> fix: deploy script fails

- package.json
> chore: Update app version

- package-lock.json
- package.json
> chore: Update package-lock.json
